# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=students-app

# ===============================
# SERVER CONFIG
# ===============================
server.port=8081

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/studentdb
spring.datasource.username=dharm
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

# ===============================
# SQL CONFIG
# ===============================
spring.sql.init.mode=always
spring.sql.init.platform=postgres
