# ===============================
# APPLICATION CONFIGURATION
# ===============================
spring.application.name=quiz-service

# ===============================
# SERVER CONFIG
# ===============================
server.port=8081

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/quiz-DB
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


