spring.application.name=api-gateway
server.port=8762

# Enable automatic route mapping
#spring.cloud.gateway.discovery.locator.enabled=true

# Optional: use lowercase service IDs
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Gateway Routes
spring.cloud.gateway.routes[0].id=question-service
spring.cloud.gateway.routes[0].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/question/**

spring.cloud.gateway.routes[1].id=quiz-service
spring.cloud.gateway.routes[1].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/quiz/**

# CORS
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true