spring.application.name=SpringJdbcEx

spring.datasource.url=jdbc:postgresql://localhost:5432/college
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

