# Application Name
spring.application.name=springboot-rest

# SERVER PORT
server.port=8080

# Datasource Configuration
#spring.datasource.url=jdbc:postgresql://my-db.c76ak0gcyd3j.ap-south-1.rds.amazonaws.com:5432/jobapp-db
spring.datasource.url=jdbc:postgresql://54.206.184.165:5432/jobapp-db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: This shows the SQL Spring is running in your console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
